# Generated by Django 2.0.2 on 2018-03-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationML', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='authorized',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
